[NOD-528] Insert blocks and transaction in chunks
kaspanet/kasparov pull request #18
Opened 2020-01-14 09:26 UTC by someone235

2020-01-14 13:44 UTC, svarogg reviewed
Sync.go has grown quite long, and has some very long functions inside them.
It is time to break it down to a few files, which will also make it more convenient to also break the longer functions into goroutines.

2020-01-14 13:44 UTC, svarogg commented on kasparovsyncd/sync.go
> +	blocksMap := make(map[string]*rawAndVerboseBlock)
Please mention what does it map to what.
Preferably in name, but if too long, than at least a comment

2020-01-14 13:44 UTC, svarogg commented on kasparovsyncd/sync.go
> +func insertBlocks(dbTx *gorm.DB, blocks []*rawAndVerboseBlock, transactionIDtoTxWithMetaData map[string]*txWithMetaData) (map[string]uint64, error) {
Please give names to outputs, as it's not easily clear what the function returns

2020-01-14 13:44 UTC, svarogg commented on kasparovsyncd/sync.go
> +func outpointSetToSqlTuples(outpointToID map[outpoint]struct{}) [][]interface{} {
Sql->SQL

2020-01-14 13:44 UTC, svarogg commented on kasparovsyncd/sync.go
> +				return errors.Errorf("couldn't find ID for outpoint (%s:%s)", txIn.TxID, txIn.Vout)
txIn.Vout is not %s, it's %d

2020-01-14 13:44 UTC, svarogg commented on kasparovsyncd/sync.go
> +	transactionIDtoTxWithMetaData, err := insertBlocksTransactions(dbTx, client, blocks)
The fact that we have `insertBlocksTransactions` and `insertTransactionsBlocks` is quite confusing.
Please consider to rename somehow some of them.

2020-01-14 13:44 UTC, svarogg commented on kasparovsyncd/sync.go
> +	transactionIDtoTxWithMetaData, err := insertBlocksTransactions(dbTx, client, blocks)
Also, I think it should be transactionID**T**oTxWithMeta**d**ata

2020-01-14 13:44 UTC, svarogg commented on kasparovsyncd/sync.go
> +	subnetworkIDToID, err := insertBlocksSubnetworks(dbTx, client, blocks)
I think maybe insertBlocksSubnetworks should be outside insertBlocksTransactions.
They are releated, but not enought to be one-part-of-the-other IMHO.

2020-01-15 09:43 UTC, stasatdaglabs requested changes

2020-01-15 09:43 UTC, stasatdaglabs commented on kasparovsyncd/sync.go
> +func fetchBlockAndMissingAncestors(client *jsonrpc.Client, block *rawAndVerboseBlock, blockExistingInMemory map[string]*rawAndVerboseBlock) ([]*rawAndVerboseBlock, error) {
Please rename this to fetchMissingAncestors.

2020-01-15 09:43 UTC, stasatdaglabs commented on kasparovsyncd/sync.go
> +func missingParentHashes(parentHashes []string, blockExistingInMemory map[string]*rawAndVerboseBlock) ([]string, error) {
Please rename blockExistingInMemory to blocksExistingInMemory.

2020-01-15 09:43 UTC, stasatdaglabs commented on kasparovsyncd/sync.go
>  	// Make sure that all the parent hashes exist in the database
Please update this comment.

2020-01-15 09:43 UTC, stasatdaglabs commented on kasparovsyncd/sync.go
> +func missingParentHashes(parentHashes []string, blockExistingInMemory map[string]*rawAndVerboseBlock) ([]string, error) {
Also, consider changing the name of the function to missingParentHashesInMemory.

2020-01-15 09:43 UTC, stasatdaglabs commented on kasparovsyncd/sync.go
> +func bulkInsert(db *gorm.DB, objects []interface{}, chunkSize int, excludeColumns ...string) error {
Instead of passing chunkSize every time you call bulkInsert, please consider just using the insertChunkSize constant in this function's body.

2020-01-15 09:43 UTC, stasatdaglabs commented on kasparovsyncd/sync.go
> +	blockHashToID := make(map[string]uint64)
Please rename this to blockHashesToIDs.

2020-01-15 09:43 UTC, stasatdaglabs commented on kasparovsyncd/sync.go
> +func getBlocksAndParentsIDs(dbTx *gorm.DB, blocks []*rawAndVerboseBlock) (map[string]uint64, error) {
Please rename this to getBlocksAndParentIDs.

2020-01-15 09:43 UTC, stasatdaglabs commented on kasparovsyncd/sync.go
> +	blockHashToID, err := getBlocksAndParentsIDs(dbTx, blocks)
Please rename this to blockHashesToIDs.

2020-01-15 09:43 UTC, stasatdaglabs commented on kasparovsyncd/sync.go
> +	blockHashToID, err := insertBlocks(dbTx, blocks, transactionIDtoTxWithMetaData)
Please rename this to blockHashesToIDs.

2020-01-15 09:43 UTC, stasatdaglabs commented on kasparovsyncd/sync.go
> +	transactionIDtoTxWithMetaData, err := insertBlocksTransactions(dbTx, client, blocks)
Please pluralize this somehow. Something like transactionIDsToTxsWithMetadata.

2020-01-15 09:43 UTC, stasatdaglabs commented on kasparovsyncd/sync.go
> +func outpointSetToSqlTuples(outpointToID map[outpoint]struct{}) [][]interface{} {
outpointToID -> outpointsToIDs

2020-01-15 09:43 UTC, stasatdaglabs commented on kasparovsyncd/sync.go
> +	addressToAddressID := make(map[string]uint64)
Please rename this to addressesToAddressIDs.

2020-01-15 09:43 UTC, stasatdaglabs commented on kasparovsyncd/sync.go
> +		return nil, httpserverutils.NewErrorFromDBErrors("failed to find blocks: ", dbErrors)
We're searching for addresses here, not blocks.

2020-01-15 09:43 UTC, stasatdaglabs commented on kasparovsyncd/sync.go
> +		return nil, httpserverutils.NewErrorFromDBErrors("failed to find blocks: ", dbErrors)
These are not blocks that we're finding here.

2020-01-15 09:43 UTC, stasatdaglabs commented on kasparovsyncd/sync.go
> +func insertBlocksSubnetworks(dbTx *gorm.DB, client *jsonrpc.Client, blocks []*rawAndVerboseBlock) (map[string]uint64, error) {
Please name the return parameters.

2020-01-15 09:43 UTC, stasatdaglabs commented on kasparovsyncd/sync.go
> +		return nil, httpserverutils.NewErrorFromDBErrors("failed to find blocks: ", dbErrors)
These are not blocks that we're failing to fine here.

2020-01-16 15:01 UTC, svarogg requested changes

2020-01-16 15:01 UTC, svarogg commented on kasparovsyncd/data_access/block.go
> +package dataaccess
Rename package to sync.
DAL we'll do later, and properly

2020-01-16 15:01 UTC, svarogg commented on kasparovsyncd/data_access/block.go
> +	err = insertTransactionBlocks(dbTx, blocks, blockHashesToIDs, transactionIDsToTxsWithMetaData)
Find a better name to not sound the same as insertBlockTransactions

2020-01-16 15:01 UTC, svarogg commented on kasparovsyncd/data_access/transaction.go
> +func insertBlocksTransactionInputs(dbTx *gorm.DB, transactionIDsToTxsWithMetaData map[string]*txWithMetaData) error {
MetaData should be spelled Metadata. Here and everywhere

2020-01-16 15:01 UTC, svarogg commented on kasparovsyncd/data_access/transaction.go
> +	inputIterator := 0
It's not an iterator, it's an index

2020-01-19 11:43 UTC, stasatdaglabs approved these changes

2020-01-19 13:23 UTC, svarogg approved these changes

2020-01-19 13:25 UTC, merged