[NOD-671] Add raw transactions and confirmations
kaspanet/kasparov pull request #25
Opened 2020-01-27 15:16 UTC by someone235

2020-01-27 16:20 UTC, svarogg requested changes

2020-01-27 16:20 UTC, svarogg commented on kasparovd/controllers/transaction.go
> +	selectedTipBlueScore, err := fetchSelectedTipBlueScore()
How about fetchSelectedTipBlueScore would be part of txConfirmations?

2020-01-27 16:20 UTC, svarogg commented on kasparovd/controllers/transaction.go
> +			confirmations = selectedTipBlueScore - *acceptingBlockBlueScore + 1
Why not use txConfirmations here?

2020-01-27 16:22 UTC, someone235 commented on kasparovd/controllers/transaction.go
> +			confirmations = selectedTipBlueScore - *acceptingBlockBlueScore + 1
Because sometimes you want to get confirmations for many transactions and you don't want to fetch selected tip for each one of them

2020-01-27 16:46 UTC, someone235 commented on kasparovd/controllers/transaction.go
> +	selectedTipBlueScore, err := fetchSelectedTipBlueScore()
Because sometimes you want to get confirmations for many transactions and you don't want to fetch selected tip for each one of them

2020-01-28 07:14 UTC, svarogg submitted a review, later dismissed

2020-01-28 07:24 UTC, stasatdaglabs requested changes

2020-01-28 07:24 UTC, stasatdaglabs commented on kasparovd/controllers/common.go
> +	if tx.RawTransaction != nil {
When will RawTransaction ever be nil? Please return an error if never.

2020-01-28 09:04 UTC, svarogg approved these changes

2020-01-28 09:23 UTC, stasatdaglabs approved these changes

2020-01-28 09:23 UTC, merged