[NOD-685] Fetch blocks missing in db when handling selectedParent-chain changes
kaspanet/kasparov pull request #34
Opened 2020-02-12 15:33 UTC by svarogg

2020-02-12 16:44 UTC, someone235 requested changes
Please remove from canHandleChainChangedMsg the part that checks if we have all of the `AddedChainBlocks`

2020-02-13 08:46 UTC, dereeno requested changes

2020-02-13 08:46 UTC, dereeno commented on kasparovsyncd/sync/sync.go
> +
redundant new line

2020-02-13 08:46 UTC, dereeno commented on kasparovsyncd/sync/sync.go
> +func fetchMissingBlock(client *jsonrpc.Client, dbTx *dbaccess.TxContext, addedBlock *rpcmodel.ChainBlock) (*dbmodels.Block, error) {
Please rename to `fetchMissingChainBlock`

2020-02-13 13:57 UTC, someone235 approved these changes

2020-02-13 13:58 UTC, dereeno approved these changes

2020-02-13 13:58 UTC, merged