[NOD-754] Fix staticcheck errors
kaspanet/kasparov pull request #43
Opened 2020-02-16 15:00 UTC by someone235

2020-02-17 13:18 UTC, dereeno submitted a review, later dismissed

2020-02-17 13:33 UTC, svarogg requested changes

2020-02-17 13:33 UTC, svarogg commented on database/log.go
> -	spawn = panics.GoroutineWrapperFunc(log)
I think it's nice we have spawn and log available even if it's not used.

2020-02-17 13:33 UTC, svarogg commented on kasparovsyncd/mqtt/log.go
> -	spawn = panics.GoroutineWrapperFunc(log)
Same here too

2020-02-19 06:54 UTC, dereeno approved these changes

2020-02-19 11:21 UTC, svarogg approved these changes

2020-02-19 11:21 UTC, merged