[NOD-758] Add confirmations to blocks
kaspanet/kasparov pull request #49
Opened 2020-02-19 15:56 UTC by someone235

2020-02-19 16:03 UTC, dereeno submitted a review, later dismissed

2020-02-20 14:36 UTC, svarogg requested changes

2020-02-20 14:36 UTC, svarogg commented on kasparovd/controllers/block.go
> +	blockRes := apimodels.ConvertBlockModelToBlockResponse(block)
Pass selectedTipBlueScore and than assign confirmations inside

2020-02-20 14:36 UTC, svarogg commented on kasparovd/controllers/block.go
> +		blockResponses[i].Confirmations = pointers.Uint64(confirmations(blockResponses[i].AcceptingBlockBlueScore, selectedTipBlueScore))
Here too

2020-02-23 09:45 UTC, svarogg submitted a review, later dismissed

2020-02-23 10:31 UTC, dereeno submitted a review, later dismissed

2020-02-24 07:04 UTC, svarogg requested changes

2020-02-24 07:04 UTC, svarogg commented on apimodels/conversions.go
> +	subnetworkID := &subnetworkid.SubnetworkID{}
Please add empty line after multi-line function declaration

2020-02-24 07:04 UTC, svarogg commented on apimodels/conversions.go
> +	isSpendable := false
Better to first calculate `isSpendable`, and only than instantiate `txOutRes`, with isSpendable already known, just as we do with `isCoinbase` and `utxoConfirmation`

2020-02-24 08:41 UTC, svarogg submitted a review, later dismissed

2020-02-25 10:05 UTC, dereeno requested changes

2020-02-25 10:05 UTC, dereeno commented on apimodels/conversions.go
> +func confirmations(acceptingBlueScore *uint64, selectedTipBlueScore uint64) uint64 {
please rename to acceptingBlockBlueScore to be consistent with the other places we use it

2020-02-25 10:10 UTC, dereeno submitted a review, later dismissed

2020-03-01 16:06 UTC, svarogg approved these changes

2020-03-01 16:09 UTC, dereeno approved these changes

2020-03-01 16:09 UTC, merged