[NOD-787] Group transactions/address/%s results by transaction ID
kaspanet/kasparov pull request #56
Opened 2020-02-26 10:12 UTC by someone235

2020-02-27 10:12 UTC, stasatdaglabs submitted a review, later dismissed

2020-02-27 11:06 UTC, svarogg requested changes

2020-02-27 11:06 UTC, svarogg commented on dbaccess/transaction.go
> +		Group("transactions.id")
The more correct way is to use SELECT DISTINCT if you are not doing any aggregates.
In Gorm you'll have to do `.Select("DISCTINCT transactions.id")`

2020-03-01 10:46 UTC, svarogg approved these changes

2020-03-01 10:49 UTC, stasatdaglabs approved these changes

2020-03-01 10:50 UTC, merged