[NOD-837] Return nil if limit=0
kaspanet/kasparov pull request #73
Opened 2020-04-23 11:27 UTC by someone235

2020-04-26 06:34 UTC, svarogg requested changes

2020-04-26 06:34 UTC, svarogg commented on dbaccess/block.go
> +		return nil, nil
Please return empty slice instead of nil.

2020-04-26 06:34 UTC, svarogg commented on dbaccess/transaction.go
> +		return nil, nil
Please return empty slice instead of nil.

2020-04-27 11:19 UTC, stasatdaglabs approved these changes

2020-04-27 11:23 UTC, svarogg approved these changes

2020-04-27 11:23 UTC, merged