[NOD-939] Optimize TransactionsByAddressCount
kaspanet/kasparov pull request #74
Opened 2020-04-23 15:58 UTC by someone235

2020-04-26 06:14 UTC, stasatdaglabs requested changes

2020-04-26 06:14 UTC, stasatdaglabs commented on dbaccess/transaction.go
> +	var res struct {
Why "res" and not "result"?

2020-04-26 06:40 UTC, stasatdaglabs approved these changes

2020-04-27 10:56 UTC, svarogg approved these changes

2020-04-27 10:57 UTC, merged